### ISSUE TITLE
System.Data.ConstraintException : Attempted to allocate a duplicate unique FormKey

### ISSUE THREAD

**Issue by SergioBaldomeroBeltranSantiago** [erri120/SilentMoonsEnchantmentPatcher.Net#98]
[Everything.txt](https://github.com/Synthesis-Collective/SilentMoonsEnchantmentPatcher.Net/files/7385174/Everything.txt)

[SilentMoonsEnchantmentPatcher.Net.txt](https://github.com/Synthesis-Collective/SilentMoonsEnchantmentPatcher.Net/files/7385175/SilentMoonsEnchantmentPatcher.Net.txt)

This happened while patching 251 plugins, i'll try the zEdit version and see if that works.

**Comment by Noggog** [comment]
Go to your profile settings at the top bar, and turn FormID persistence to `None`.  It should be off by default but I think somehow that got turned on for people

**Comment by SergioBaldomeroBeltranSantiago** [comment]
[Everything.txt](https://github.com/Synthesis-Collective/SilentMoonsEnchantmentPatcher.Net/files/7385628/Everything.txt)

[SilentMoonsEnchantmentPatcher.Net.txt](https://github.com/Synthesis-Collective/SilentMoonsEnchantmentPatcher.Net/files/7385630/SilentMoonsEnchantmentPatcher.Net.txt)

Same error with FormID persistence set to None. I'm using MO2 and Skyrim LE

**Comment by Noggog** [comment]
Gotcha, yeah, I'm seeing a few subtle things are bit off, which I'll be patching up on Synthesis.

In the meantime, try deleting the file/folder found here:
`C:\Users\pokem\AppData\Local\Temp\Synthesis\bepnqowf.nby\Persistence`

**Comment by Noggog** [comment]
Just pushed out Synthesis v0.20.4 to address some of the issues as well.  Reopen if you're still having problems
