### ISSUE TITLE
Patcher Errors

### ISSUE THREAD

**Issue by Cloud-and-Proud** [erri120/SilentMoonsEnchantmentPatcher.Net#99]
Hej, sorry if I shouldn't be putting this here, but I'm having some kind of error when I run the patcher
I can send you the log if you want

**Comment by Noggog** [comment]
Yeah, logs or some other readout of the errors would be useful

**Comment by Cloud-and-Proud** [comment]
[Silent Moons Synthesis Patcher Crash Log.txt](https://github.com/Synthesis-Collective/SilentMoonsEnchantmentPatcher.Net/files/7803469/Silent.Moons.Synthesis.Patcher.Crash.Log.txt)
Hope this helps
I also hope there isn't any sensitive info about my computer in there >..<

**Comment by Noggog** [comment]
Go to profile settings -> FormID Persistence -> turn to `None`
